# Generated by Django 2.1.4 on 2018-12-13 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128)),
                ('last_name', models.CharField(blank=True, max_length=128)),
                ('avatar', models.ImageField(blank=True, upload_to='avatars')),
                ('birthday', models.DateField(blank=True, default='1990-12-01')),
                ('town', models.CharField(blank=True, max_length=128)),
                ('visible_name', models.CharField(blank=True, max_length=128)),
                ('url', models.CharField(blank=True, max_length=256)),
                ('contact_number', models.CharField(blank=True, max_length=32)),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
