# Generated by Django 2.1.4 on 2018-12-13 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('checked_out', models.BooleanField(default=False, verbose_name='checked out')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile')),
            ],
            options={
                'verbose_name': 'cart',
                'ordering': ('-creation_date',),
                'verbose_name_plural': 'carts',
            },
        ),
        migrations.CreateModel(
            name='HairProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='hair length')),
                ('colour', models.CharField(blank=True, max_length=128)),
                ('greasy', models.BooleanField(default=False)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HairType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=128)),
                ('texture', models.CharField(blank=True, max_length=128)),
                ('porosity', models.CharField(blank=True, max_length=128)),
                ('tenacity', models.CharField(blank=True, max_length=128)),
                ('density', models.CharField(blank=True, max_length=128)),
                ('elasticity', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=18, verbose_name='unit_price')),
                ('object_id', models.PositiveIntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haircare.Cart', verbose_name='cart')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'item',
                'ordering': ('cart',),
                'verbose_name_plural': 'items',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('active', models.BooleanField(default=True, help_text='Is this product publicly visible.', verbose_name='Active')),
                ('isbn', models.CharField(max_length=255)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(blank=True, null=True, upload_to='fileuploads\\%Y\\%m\\%d')),
                ('ratings', models.CharField(blank=True, choices=[('1', 'Worst'), ('2', 'Bed'), ('3', 'Average'), ('4', 'Good'), ('5', 'Best')], db_index=True, max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=35)),
                ('slug', models.CharField(max_length=250)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='product', to='haircare.Tag'),
        ),
        migrations.AddField(
            model_name='hairprofile',
            name='hair_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='haircare.HairType', verbose_name='hair type'),
        ),
        migrations.AddField(
            model_name='hairprofile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.UserProfile'),
        ),
    ]
